@baseUrl=http://localhost:3000


### Register a new user
POST {{baseUrl}}/auth/register 
Content-Type: application/json

{
    "username": "Xavier",
    "password": "123456"
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "Xavier",
    "password": "123456"
}



### Get all users
GET {{baseUrl}}/users



### Get user by id
GET {{baseUrl}}/users/6723ebd20ac5e91ecd33ae1b

